package fr.lezoo.stonks.api.quotation;

import fr.lezoo.stonks.Stonks;
import org.bukkit.Bukkit;
import org.bukkit.configuration.ConfigurationSection;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

/**
 * Quotation which handles Vault economy
 */
public class CreatedQuotation extends Quotation {
    private double previousDemand = 0;
    private double currentDemand = 0;


    //Created Quotations are generated by algorithms and don't follow the trend of real life markets.

    public CreatedQuotation(String id, String companyName, String stockName, List<QuotationInfo> quarterHourData, List<QuotationInfo> hourData, List<QuotationInfo> dayData, List<QuotationInfo> weekData, List<QuotationInfo> monthData, List<QuotationInfo> yearData, Dividends dividends) {
        super(id, companyName, stockName, quarterHourData, hourData, dayData, weekData, monthData, yearData, dividends);
    }

    public CreatedQuotation(String id, String companyName, String stockName, Dividends dividends, QuotationInfo firstQuotationData) {
        super(id, companyName, stockName, dividends, firstQuotationData);
    }

    public CreatedQuotation(ConfigurationSection config) {
        super(config);

    }


    /**
     * Changes the quotation price
     */
    public void refreshQuotation() {

        if (quarterHourData.size() == 0) {

            return;
        }
        Random random = new Random();
        double rand = random.nextInt(2);
        double change = rand == 0 ? -1 : 1;
        // The offset due to the offer and demand of the stock
        double offset = Stonks.plugin.configManager.offerDemandImpact * Math.atan(previousDemand) * 2 / Math.PI;
        double currentPrice = quarterHourData.get(quarterHourData.size() - 1).getPrice();
        //The change between the currentPrice and nextPrice

        //We multiply by sqrt(t) so that volatility doesn't depend on refreshTime

        change = (change + offset) * Stonks.plugin.configManager.volatility * currentPrice / 20 * Math.sqrt((double) (Stonks.plugin.configManager.quotationRefreshTime) / 3600);

        int datanumber = Stonks.plugin.configManager.quotationDataNumber;
        //We update all the data List
        for (QuotationTimeDisplay time : QuotationTimeDisplay.values()) {
            //We get the list corresponding to the time
            List<QuotationInfo> workingData = this.getCorrespondingData(time);
            //If the the latest data of workingData is too old we add another one
            if (System.currentTimeMillis() - workingData.get(workingData.size() - 1).getTimeStamp() > time.getTime() / datanumber) {


                workingData.add(new QuotationInfo(System.currentTimeMillis(), currentPrice + change));
                //If the list contains too much data we remove the older ones
                if (workingData.size() > datanumber)
                    workingData.remove(0);
                //We save the changes we made in the attribute
                this.setCorrespondingData(time, workingData);
            }


        }

    }


    public void addDemand(double stockBought) {
        currentDemand += stockBought;
    }
}
